# Generated by Django 6.0.4 on 2026-04-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Completada', 'Completada'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
