# Generated by Django 6.0.4 on 2026-04-24 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Zona')),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Imagen de Zona')),
            ],
            options={
                'verbose_name': 'Zona/Ubicación',
                'verbose_name_plural': 'Zonas/Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Número de Mesa')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Capacidad')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=20)),
                ('shape', models.CharField(choices=[('rect', 'Rectangular'), ('circle', 'Circular')], default='rect', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='table_manager.location')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'unique_together': {('location', 'number')},
            },
        ),
    ]
