# Generated by Django 6.0.4 on 2026-04-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen de Fondo (Base64/URL)'),
        ),
    ]
