# Generated by Django 6.0.4 on 2026-04-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_manager', '0002_alter_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='table',
            name='x',
        ),
        migrations.RemoveField(
            model_name='table',
            name='y',
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Imagen de Zona'),
        ),
    ]
