# Generated by Django 6.0.4 on 2026-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nosotros', max_length=200, verbose_name='Título Sección')),
                ('years_value', models.CharField(default='15', max_length=50, verbose_name='Valor Insignia (Ej: Años)')),
                ('years_label', models.CharField(default='Años de Excelencia', max_length=100, verbose_name='Texto Insignia')),
                ('images', models.JSONField(blank=True, default=list, help_text='Lista de URLs o imágenes Base64', verbose_name='Galería de Fotos')),
                ('content', models.TextField(default='Historia del restaurante...', verbose_name='Contenido de Historia')),
                ('feature_1_title', models.CharField(default='Alta Cocina', max_length=100, verbose_name='Título Característica 1')),
                ('feature_1_desc', models.CharField(default='Ingredientes premium', max_length=255, verbose_name='Desc. Característica 1')),
                ('feature_2_title', models.CharField(default='Diseño Urbano', max_length=100, verbose_name='Título Característica 2')),
                ('feature_2_desc', models.CharField(default='Atmósfera única', max_length=255, verbose_name='Desc. Característica 2')),
            ],
            options={
                'verbose_name': 'Sección Nosotros',
                'verbose_name_plural': 'Sección Nosotros',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Calle 123, Ciudad', max_length=255, verbose_name='Dirección Física')),
                ('phone', models.CharField(default='+1 234 567 890', max_length=100, verbose_name='Teléfono de Contacto')),
                ('email', models.EmailField(default='contacto@urbangourmet.com', max_length=254, verbose_name='Email Público')),
                ('instagram', models.CharField(default='@urbangourmet', max_length=100, verbose_name='Instagram')),
                ('whatsapp_prefix', models.CharField(default='57', max_length=10, verbose_name='Indicativo WhatsApp (Ej: 57)')),
            ],
            options={
                'verbose_name': 'Información de Contacto',
                'verbose_name_plural': 'Información de Contacto',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='URBAN GOURMET', max_length=200, verbose_name='Título Principal')),
                ('subtitle', models.CharField(default='Experiencia Gastronómica', max_length=255, verbose_name='Subtítulo')),
                ('established', models.CharField(default='EST. 2024', max_length=100, verbose_name='Texto Vertical (Año)')),
                ('cta_menu', models.CharField(default='Ver Carta Completa', max_length=100, verbose_name='Texto Botón Carta')),
                ('cta_reserva', models.CharField(default='Reservar Mesa', max_length=100, verbose_name='Texto Botón Reserva')),
                ('featured_image', models.TextField(blank=True, null=True, verbose_name='Imagen de Respaldo (URL o Base64)')),
                ('featured_name', models.CharField(default='Truffle Burger', max_length=100, verbose_name='Nombre de Respaldo')),
                ('featured_price', models.CharField(default='$24', max_length=50, verbose_name='Precio de Respaldo')),
                ('featured_desc', models.CharField(default='Angus beef, truffle mayo, brioche.', max_length=255, verbose_name='Descripción de Respaldo')),
                ('stats_label', models.CharField(default='Trending', max_length=100, verbose_name='Etiqueta Stats')),
                ('stats_value', models.CharField(default='+124 Pedidos', max_length=100, verbose_name='Valor Stats')),
            ],
            options={
                'verbose_name': 'Sección Hero (Principal)',
                'verbose_name_plural': 'Sección Hero (Principal)',
            },
        ),
        migrations.CreateModel(
            name='ReservationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Reservaciones', max_length=200, verbose_name='Título de Reserva')),
                ('subtitle', models.CharField(default='Asegura tu experiencia', max_length=255, verbose_name='Subtítulo / Slogan')),
                ('help_text', models.CharField(default='Para reservas de más de 8 personas, contáctanos por teléfono.', max_length=255, verbose_name='Texto de Ayuda (Pax)')),
            ],
            options={
                'verbose_name': 'Sección de Reservas',
                'verbose_name_plural': 'Sección de Reservas',
            },
        ),
        migrations.DeleteModel(
            name='CMSSection',
        ),
        migrations.AlterModelOptions(
            name='systemnotification',
            options={'verbose_name': 'Notificación del Sistema', 'verbose_name_plural': 'Notificaciones del Sistema'},
        ),
    ]
