# Generated by Django 6.0.4 on 2026-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Experience the city through flavor.', max_length=500, verbose_name='Descripción Footer')),
                ('socials', models.JSONField(blank=True, default=list, verbose_name='Redes Sociales')),
                ('copyright', models.CharField(default='Digital Gastronomy', max_length=200, verbose_name='Texto Copyright')),
            ],
            options={
                'verbose_name': 'Pie de Página (Footer)',
                'verbose_name_plural': 'Pie de Página (Footer)',
            },
        ),
    ]
