# Generated by Django 6.0.4 on 2026-04-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_manager', '0002_footersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsection',
            name='closed_image',
            field=models.TextField(blank=True, null=True, verbose_name="Imagen de 'Cerrado' (URL o Base64)"),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='closing_time',
            field=models.TimeField(default='22:00:00', verbose_name='Hora de Cierre'),
        ),
        migrations.AddField(
            model_name='contactsection',
            name='opening_time',
            field=models.TimeField(default='08:00:00', verbose_name='Hora de Apertura'),
        ),
    ]
