# Generated by Django 6.0.4 on 2026-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_manager', '0002_aboutsection_contactsection_herosection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='URBAN STREET', max_length=100, verbose_name='Nombre del Restaurante')),
                ('tagline', models.CharField(default='Control Center', max_length=200, verbose_name='Eslogan / Tagline')),
            ],
            options={
                'verbose_name': 'Identidad de Marca',
                'verbose_name_plural': 'Identidad de Marca',
            },
        ),
    ]
