# Generated by Django 6.0.4 on 2026-04-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_vegetarian',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spicy_level',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Precio'),
        ),
    ]
