# Generated by Django 6.0.4 on 2026-04-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('dashboard_view', 'Ver Dashboard'), ('reservations_manage', 'Gestionar Reservas'), ('tables_manage', 'Gestionar Mesas (Infraestructura)'), ('orders_manage', 'Gestionar Pedidos'), ('products_manage', 'Gestionar Menú y Productos'), ('kitchen_view', 'Ver Display de Cocina'), ('cms_manage', 'Gestionar Contenido CMS'), ('system_settings', 'Gestionar Configuración y Personal'), ('delivery_manage', 'Gestionar Domicilios')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
