# Generated by Django 6.0.4 on 2026-04-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Efectivo'), ('Card', 'Tarjeta'), ('Transfer', 'Transferencia')], max_length=50, null=True),
        ),
    ]
