# Generated by Django 6.0.4 on 2026-04-23 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0002_order_customer_id'),
        ('reservation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='reservation_manager.reservation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(default='$0.00', max_length=50, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.CharField(max_length=50, verbose_name='Precio (Copia)'),
        ),
    ]
