# Generated by Django 6.0.4 on 2026-04-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0004_order_is_paid_order_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
