# Generated by Django 6.0.4 on 2026-04-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0005_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('En Lista', 'En Lista'), ('Preparando', 'Preparando'), ('Listo', 'Listo'), ('Completado', 'Completado'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
